otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=http://localhost:4317
otel.resource.attributes=deployment.environment=local,service.namespace=ticket-v2
otel.propagators=tracecontext,baggage
otel.instrumentation.messaging.experimental.receive-telemetry.enabled=true
otel.instrumentation.common.db-statement-sanitizer.enabled=true
