export const tmTokens = {
  colors: {
    background: "#f9f9fe",
    surface: "#f9f9fe",
    surfaceLowest: "#ffffff",
    surfaceLow: "#f3f3f8",
    surfaceContainer: "#ededf2",
    surfaceHigh: "#e8e8ed",
    surfaceHighest: "#e2e2e7",
    onSurface: "#1a1c1f",
    secondary: "#5f5e5e",
    primary: "#7f0900",
    primaryContainer: "#aa1101",
    error: "#ba1a1a",
    border: "#e8e8ed",
  },
  layout: {
    sidebarWidth: 72,
    topbarHeight: 64,
    pageMargin: 32,
    maxContentWidth: 1280,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12,
    full: 9999,
  },
  spacing: {
    stackSm: 4,
    stackMd: 12,
    stackLg: 24,
  },
  typography: {
    headlineXl: {
      fontFamily: "\"Outfit\", Arial, sans-serif",
      fontSize: "32px",
      fontWeight: 600,
      lineHeight: "40px",
      letterSpacing: 0,
    },
    headlineLg: {
      fontFamily: "\"Outfit\", Arial, sans-serif",
      fontSize: "24px",
      fontWeight: 600,
      lineHeight: "32px",
      letterSpacing: 0,
    },
    headlineMd: {
      fontFamily: "\"Outfit\", Arial, sans-serif",
      fontSize: "20px",
      fontWeight: 600,
      lineHeight: "28px",
      letterSpacing: 0,
    },
    headlineSm: {
      fontFamily: "\"Outfit\", Arial, sans-serif",
      fontSize: "16px",
      fontWeight: 600,
      lineHeight: "24px",
      letterSpacing: 0,
    },
    bodyMd: {
      fontFamily: "\"DM Sans\", Arial, sans-serif",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "20px",
      letterSpacing: 0,
    },
    bodyMdBold: {
      fontFamily: "\"DM Sans\", Arial, sans-serif",
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: 0,
    },
    labelSm: {
      fontFamily: "\"DM Sans\", Arial, sans-serif",
      fontSize: "12px",
      fontWeight: 500,
      lineHeight: "16px",
      letterSpacing: "0.02em",
    },
  },
} as const;
